# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Hotel-Booking application docker image to hub and azure app

on:
  push:
    branches:
      - release-*
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: 'hotel-booking'
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/mfdemo.hotel-booking:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mfdemohotelbooking'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_15a502a75c7a4f04bf5f749774e0ff86 }}
        images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/mfdemo.hotel-booking:${{ github.sha }}'
