name: Publish docker images for Applications

on:
  push:
    branches: [ "main" ]

jobs:
  build-shell:
    name: Build shell application Docker image

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'shell'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: stijnboss12/mfdemo.shell

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: 'shell'
        push: true
        tags: stijnboss12/mfdemo.shell:latest
        labels: ${{ steps.meta.outputs.labels }}
        
  deploy-shell:
    runs-on: ubuntu-latest
    needs: build-shell
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mfdemoshell'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4dfa9e31acdd418d80f775ecdc395de9 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7c9732dd819344f689705f29a35d8eaa }}/mfdemo.shell:latest'

  build-hotel-booking:
    name: Build hotel-booking application Docker image

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'hotel-booking'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: stijnboss12/mfdemo.hotel-booking

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: 'hotel-booking'
        push: true
        tags: stijnboss12/mfdemo.hotel-booking:latest
        labels: ${{ steps.meta.outputs.labels }}

  build-flight-booking:
    name: Build flight-booking application Docker image

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'flight-booking'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: stijnboss12/mfdemo.flight-booking

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: 'flight-booking'
        push: true
        tags: stijnboss12/mfdemo.flight-booking:latest
        labels: ${{ steps.meta.outputs.labels }}
